### ISSUE TITLE
Suggested Changes

### ISSUE THREAD

**Issue by romitkarmakar** [Soupaul/GLUG-App#3]
- [x] Use Dio instead of HTTP package. https://pub.dev/packages/dio
- [ ] Add support for Flutter Web. (This is highly recommended as in future it will reduce our dependency on separate codebase for glug website)
- [x] Use Codemagic CI to release debug artifacts of this project. https://codemagic.io/
- [x] Use flutter_webview_plugin instead of webview_flutter https://pub.dev/packages/flutter_webview_plugin

**Comment by Soupaul** [comment]
Got it
